name: pr-checks
run-name: PRs to main - install packages and run lint
on: 
  pull_request:
    branches: 
       - main
jobs:
  install_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i
      - run: npm run lint
