name: run-tests
run-name: Install packages and run lint
on: [pull_request]
jobs:
  install and lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i
      - run: npm run lint
